### ISSUE TITLE
📌 [work breakdown] Region stake and unstake 

### ISSUE THREAD

**Issue by jagodarybacka** [tahowallet/dapp#137]
```[tasklist]
### Tasks
- [ ] https://github.com/tahowallet/dapp/issues/140
- [ ] https://github.com/tahowallet/dapp/issues/142
- [ ] https://github.com/tahowallet/dapp/issues/139
- [ ] https://github.com/tahowallet/dapp/issues/143
- [ ] https://github.com/tahowallet/dapp/issues/144
- [ ] https://github.com/tahowallet/dapp/issues/147
- [ ] https://github.com/tahowallet/dapp/issues/145
- [ ] https://github.com/tahowallet/dapp/issues/146
- [ ] https://github.com/tahowallet/dapp/issues/148
- [ ] https://github.com/tahowallet/dapp/issues/141
- [ ] https://github.com/tahowallet/dapp/issues/149
- [ ] https://github.com/tahowallet/dapp/issues/150
- [ ] https://github.com/tahowallet/dapp/issues/151
- [ ] https://github.com/tahowallet/dapp/issues/138
```
