### ISSUE TITLE
Region and rewards work breakdown

### ISSUE THREAD

**Issue by jagodarybacka** [tahowallet/dapp#175]
```[tasklist]
### Tasks
- [ ] https://github.com/tahowallet/dapp/issues/176
- [ ] https://github.com/tahowallet/dapp/issues/177
- [ ] https://github.com/tahowallet/dapp/issues/178
- [ ] https://github.com/tahowallet/dapp/issues/179
- [ ] https://github.com/tahowallet/dapp/issues/180
- [ ] https://github.com/tahowallet/dapp/issues/181
- [ ] https://github.com/tahowallet/dapp/issues/182
```
