### ISSUE TITLE
Beta Release checklist

### ISSUE THREAD

**Issue by jagodarybacka** [tahowallet/dapp#537]
- [x] finish all last-call changes
- [x] do a release checklist on stage
- [x] merge to release

Just before the release
- [x] merge https://github.com/tahowallet/dapp/pull/518 to release in a second batch, then https://github.com/tahowallet/dapp/pull/552
- [x] https://github.com/tahowallet/taho.xyz/pull/178
- [x] make sure taho.xyz has rebuilt
- [x] switch the `coming soon` flag on dapp's netlify config on prod env
- [x] rebuild dapp release branch
